# To run docker
# docker-compose -f docker-compose.dev.yml up

version: '2'
name: capstone
services:
  capstone-nginx-loadbalancer:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./loadbalancer.default.conf:/etc/nginx/conf.d/default.conf
  capstone-nginx-proxy:
    image: nginx:latest
    deploy:
      mode: replicated
      replicas: 5
    volumes:
      - ./proxy.default.conf:/etc/nginx/conf.d/default.conf
      - ../../:/app
  capstone-php-fpm:
    build:
      context: .
      dockerfile: PHP.dev.Dockerfile
    volumes:
      - ../../:/app
  capstone-mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
    - ../../assetmanagement.sql:/docker-entrypoint-initdb.d/dump.sql
  capstone-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: capstone-mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"